[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dde_solve"
version = "0.1"
description = "DDE solver"
authors = [{name = "Kaique Oliveira"}]
license = "MIT"

[tool.setuptools]
packages = ["DDE_solver"]
